#ifndef __SENTIENT_CORE_C_INTERNAL_FOREACH_H__
#define __SENTIENT_CORE_C_INTERNAL_FOREACH_H__

#ifdef __cplusplus
extern "C"
{
#endif

#define SENTIENT_INTERNAL_FOREACH0(...)
#define SENTIENT_INTERNAL_FOREACH1(X, _0, ...) X (_0) SENTIENT_INTERNAL_FOREACH0 (X, __VA_ARGS__)
#define SENTIENT_INTERNAL_FOREACH2(X, _0, ...) X (_0) SENTIENT_INTERNAL_FOREACH1 (X, __VA_ARGS__)
#define SENTIENT_INTERNAL_FOREACH3(X, _0, ...) X (_0) SENTIENT_INTERNAL_FOREACH2 (X, __VA_ARGS__)
#define SENTIENT_INTERNAL_FOREACH4(X, _0, ...) X (_0) SENTIENT_INTERNAL_FOREACH3 (X, __VA_ARGS__)
#define SENTIENT_INTERNAL_FOREACH5(X, _0, ...) X (_0) SENTIENT_INTERNAL_FOREACH4 (X, __VA_ARGS__)
#define SENTIENT_INTERNAL_FOREACH6(X, _0, ...) X (_0) SENTIENT_INTERNAL_FOREACH5 (X, __VA_ARGS__)
#define SENTIENT_INTERNAL_FOREACH7(X, _0, ...) X (_0) SENTIENT_INTERNAL_FOREACH6 (X, __VA_ARGS__)

#ifdef __cplusplus
}
#endif

#endif