#ifndef __SENTIENT_CORE_C_INTERNAL_FOREACH_H__
#define __SENTIENT_CORE_C_INTERNAL_FOREACH_H__

/**
 * @file foreach.h
 * @author Jin (jaehwanspin@gmail.com)
 * @brief preprocessor static foreach expressions
 * @version 0.1
 * @date 2022-04-05
 *
 * @copyright Copyright (c) 2022
 *
 */

#ifdef __cplusplus
extern "C"
{
#endif

#define SENTIENT_INTERNAL_FOREACH(...) SENTIENT_INTERNAL_FOREACH0(__VA_ARGS__)
#define SENTIENT_INTERNAL_FOREACH0(...)
#define SENTIENT_INTERNAL_FOREACH1(X, _0, ...) X(_0) SENTIENT_INTERNAL_FOREACH0 (X, __VA_ARGS__)
#define SENTIENT_INTERNAL_FOREACH2(X, _0, ...) X(_0) SENTIENT_INTERNAL_FOREACH1 (X, __VA_ARGS__)
#define SENTIENT_INTERNAL_FOREACH3(X, _0, ...) X(_0) SENTIENT_INTERNAL_FOREACH2 (X, __VA_ARGS__)
#define SENTIENT_INTERNAL_FOREACH4(X, _0, ...) X(_0) SENTIENT_INTERNAL_FOREACH3 (X, __VA_ARGS__)
#define SENTIENT_INTERNAL_FOREACH5(X, _0, ...) X(_0) SENTIENT_INTERNAL_FOREACH4 (X, __VA_ARGS__)
#define SENTIENT_INTERNAL_FOREACH6(X, _0, ...) X(_0) SENTIENT_INTERNAL_FOREACH5 (X, __VA_ARGS__)
#define SENTIENT_INTERNAL_FOREACH7(X, _0, ...) X(_0) SENTIENT_INTERNAL_FOREACH6 (X, __VA_ARGS__)
#define SENTIENT_INTERNAL_FOREACH8(X, _0, ...) X(_0) SENTIENT_INTERNAL_FOREACH7 (X, __VA_ARGS__)
#define SENTIENT_INTERNAL_FOREACH9(X, _0, ...) X(_0) SENTIENT_INTERNAL_FOREACH8 (X, __VA_ARGS__)
#define SENTIENT_INTERNAL_FOREACH10(X, _0, ...) X(_0) SENTIENT_INTERNAL_FOREACH9 (X, __VA_ARGS__)
#define SENTIENT_INTERNAL_FOREACH11(X, _0, ...) X(_0) SENTIENT_INTERNAL_FOREACH10 (X, __VA_ARGS__)
#define SENTIENT_INTERNAL_FOREACH12(X, _0, ...) X(_0) SENTIENT_INTERNAL_FOREACH11 (X, __VA_ARGS__)
#define SENTIENT_INTERNAL_FOREACH13(X, _0, ...) X(_0) SENTIENT_INTERNAL_FOREACH12 (X, __VA_ARGS__)
#define SENTIENT_INTERNAL_FOREACH14(X, _0, ...) X(_0) SENTIENT_INTERNAL_FOREACH13 (X, __VA_ARGS__)
#define SENTIENT_INTERNAL_FOREACH15(X, _0, ...) X(_0) SENTIENT_INTERNAL_FOREACH14 (X, __VA_ARGS__)
#define SENTIENT_INTERNAL_FOREACH16(X, _0, ...) X(_0) SENTIENT_INTERNAL_FOREACH15 (X, __VA_ARGS__)
#define SENTIENT_INTERNAL_FOREACH17(X, _0, ...) X(_0) SENTIENT_INTERNAL_FOREACH16 (X, __VA_ARGS__)
#define SENTIENT_INTERNAL_FOREACH18(X, _0, ...) X(_0) SENTIENT_INTERNAL_FOREACH17 (X, __VA_ARGS__)
#define SENTIENT_INTERNAL_FOREACH19(X, _0, ...) X(_0) SENTIENT_INTERNAL_FOREACH18 (X, __VA_ARGS__)
#define SENTIENT_INTERNAL_FOREACH20(X, _0, ...) X(_0) SENTIENT_INTERNAL_FOREACH19 (X, __VA_ARGS__)
#define SENTIENT_INTERNAL_FOREACH21(X, _0, ...) X(_0) SENTIENT_INTERNAL_FOREACH20 (X, __VA_ARGS__)
#define SENTIENT_INTERNAL_FOREACH22(X, _0, ...) X(_0) SENTIENT_INTERNAL_FOREACH21 (X, __VA_ARGS__)
#define SENTIENT_INTERNAL_FOREACH23(X, _0, ...) X(_0) SENTIENT_INTERNAL_FOREACH22 (X, __VA_ARGS__)
#define SENTIENT_INTERNAL_FOREACH24(X, _0, ...) X(_0) SENTIENT_INTERNAL_FOREACH23 (X, __VA_ARGS__)
#define SENTIENT_INTERNAL_FOREACH25(X, _0, ...) X(_0) SENTIENT_INTERNAL_FOREACH24 (X, __VA_ARGS__)
#define SENTIENT_INTERNAL_FOREACH26(X, _0, ...) X(_0) SENTIENT_INTERNAL_FOREACH25 (X, __VA_ARGS__)
#define SENTIENT_INTERNAL_FOREACH27(X, _0, ...) X(_0) SENTIENT_INTERNAL_FOREACH26 (X, __VA_ARGS__)
#define SENTIENT_INTERNAL_FOREACH28(X, _0, ...) X(_0) SENTIENT_INTERNAL_FOREACH27 (X, __VA_ARGS__)
#define SENTIENT_INTERNAL_FOREACH29(X, _0, ...) X(_0) SENTIENT_INTERNAL_FOREACH28 (X, __VA_ARGS__)
#define SENTIENT_INTERNAL_FOREACH30(X, _0, ...) X(_0) SENTIENT_INTERNAL_FOREACH29 (X, __VA_ARGS__)
#define SENTIENT_INTERNAL_FOREACH31(X, _0, ...) X(_0) SENTIENT_INTERNAL_FOREACH30 (X, __VA_ARGS__)
#define SENTIENT_INTERNAL_FOREACH32(X, _0, ...) X(_0) SENTIENT_INTERNAL_FOREACH31 (X, __VA_ARGS__)
#define SENTIENT_INTERNAL_FOREACH33(X, _0, ...) X(_0) SENTIENT_INTERNAL_FOREACH32 (X, __VA_ARGS__)
#define SENTIENT_INTERNAL_FOREACH34(X, _0, ...) X(_0) SENTIENT_INTERNAL_FOREACH33 (X, __VA_ARGS__)
#define SENTIENT_INTERNAL_FOREACH35(X, _0, ...) X(_0) SENTIENT_INTERNAL_FOREACH34 (X, __VA_ARGS__)
#define SENTIENT_INTERNAL_FOREACH36(X, _0, ...) X(_0) SENTIENT_INTERNAL_FOREACH35 (X, __VA_ARGS__)
#define SENTIENT_INTERNAL_FOREACH37(X, _0, ...) X(_0) SENTIENT_INTERNAL_FOREACH36 (X, __VA_ARGS__)
#define SENTIENT_INTERNAL_FOREACH38(X, _0, ...) X(_0) SENTIENT_INTERNAL_FOREACH37 (X, __VA_ARGS__)
#define SENTIENT_INTERNAL_FOREACH39(X, _0, ...) X(_0) SENTIENT_INTERNAL_FOREACH38 (X, __VA_ARGS__)
#define SENTIENT_INTERNAL_FOREACH40(X, _0, ...) X(_0) SENTIENT_INTERNAL_FOREACH39 (X, __VA_ARGS__)
#define SENTIENT_INTERNAL_FOREACH41(X, _0, ...) X(_0) SENTIENT_INTERNAL_FOREACH40 (X, __VA_ARGS__)
#define SENTIENT_INTERNAL_FOREACH42(X, _0, ...) X(_0) SENTIENT_INTERNAL_FOREACH41 (X, __VA_ARGS__)
#define SENTIENT_INTERNAL_FOREACH43(X, _0, ...) X(_0) SENTIENT_INTERNAL_FOREACH42 (X, __VA_ARGS__)
#define SENTIENT_INTERNAL_FOREACH44(X, _0, ...) X(_0) SENTIENT_INTERNAL_FOREACH43 (X, __VA_ARGS__)
#define SENTIENT_INTERNAL_FOREACH45(X, _0, ...) X(_0) SENTIENT_INTERNAL_FOREACH44 (X, __VA_ARGS__)
#define SENTIENT_INTERNAL_FOREACH46(X, _0, ...) X(_0) SENTIENT_INTERNAL_FOREACH45 (X, __VA_ARGS__)
#define SENTIENT_INTERNAL_FOREACH47(X, _0, ...) X(_0) SENTIENT_INTERNAL_FOREACH46 (X, __VA_ARGS__)
#define SENTIENT_INTERNAL_FOREACH48(X, _0, ...) X(_0) SENTIENT_INTERNAL_FOREACH47 (X, __VA_ARGS__)
#define SENTIENT_INTERNAL_FOREACH49(X, _0, ...) X(_0) SENTIENT_INTERNAL_FOREACH48 (X, __VA_ARGS__)
#define SENTIENT_INTERNAL_FOREACH50(X, _0, ...) X(_0) SENTIENT_INTERNAL_FOREACH49 (X, __VA_ARGS__)
#define SENTIENT_INTERNAL_FOREACH51(X, _0, ...) X(_0) SENTIENT_INTERNAL_FOREACH50 (X, __VA_ARGS__)
#define SENTIENT_INTERNAL_FOREACH52(X, _0, ...) X(_0) SENTIENT_INTERNAL_FOREACH51 (X, __VA_ARGS__)
#define SENTIENT_INTERNAL_FOREACH53(X, _0, ...) X(_0) SENTIENT_INTERNAL_FOREACH52 (X, __VA_ARGS__)
#define SENTIENT_INTERNAL_FOREACH54(X, _0, ...) X(_0) SENTIENT_INTERNAL_FOREACH53 (X, __VA_ARGS__)
#define SENTIENT_INTERNAL_FOREACH55(X, _0, ...) X(_0) SENTIENT_INTERNAL_FOREACH54 (X, __VA_ARGS__)
#define SENTIENT_INTERNAL_FOREACH56(X, _0, ...) X(_0) SENTIENT_INTERNAL_FOREACH55 (X, __VA_ARGS__)
#define SENTIENT_INTERNAL_FOREACH57(X, _0, ...) X(_0) SENTIENT_INTERNAL_FOREACH56 (X, __VA_ARGS__)
#define SENTIENT_INTERNAL_FOREACH58(X, _0, ...) X(_0) SENTIENT_INTERNAL_FOREACH57 (X, __VA_ARGS__)
#define SENTIENT_INTERNAL_FOREACH59(X, _0, ...) X(_0) SENTIENT_INTERNAL_FOREACH58 (X, __VA_ARGS__)
#define SENTIENT_INTERNAL_FOREACH60(X, _0, ...) X(_0) SENTIENT_INTERNAL_FOREACH59 (X, __VA_ARGS__)
#define SENTIENT_INTERNAL_FOREACH61(X, _0, ...) X(_0) SENTIENT_INTERNAL_FOREACH60 (X, __VA_ARGS__)
#define SENTIENT_INTERNAL_FOREACH62(X, _0, ...) X(_0) SENTIENT_INTERNAL_FOREACH61 (X, __VA_ARGS__)
#define SENTIENT_INTERNAL_FOREACH63(X, _0, ...) X(_0) SENTIENT_INTERNAL_FOREACH62 (X, __VA_ARGS__)



#ifdef __cplusplus
}
#endif

#endif