#ifndef __SENTIENT_CORE_ERROR_CHECKER_TYPES_H__
#define __SENTIENT_CORE_ERROR_CHECKER_TYPES_H__

/**
 * @file error_detection_types.h
 * @author Jin (jaehwanspin@gmail.com)
 * @brief defines error detection types enumerations
 * 
 * https://blog.naver.com/PostView.nhn?isHttpsRedirect=true&blogId=dolicom&logNo=10070824912
 * 
 * @version 0.1
 * @date 2022-04-10
 *
 * @copyright Copyright (c) 2022
 *
 */

#ifdef __cplusplus
extern "C"
{
#endif

enum sentient_error_checker_types
{
    SENTIENT_ERROR_CHECKER_TYPES_NONE,
    SENTIENT_ERROR_CHECKER_TYPES_CRC1,
    SENTIENT_ERROR_CHECKER_TYPES_CRC5,
    SENTIENT_ERROR_CHECKER_TYPES_CRC7,
    SENTIENT_ERROR_CHECKER_TYPES_CRC8,
    SENTIENT_ERROR_CHECKER_TYPES_CRC8_FLETCHER,
    SENTIENT_ERROR_CHECKER_TYPES_CRC16_FLETCHER,
    SENTIENT_ERROR_CHECKER_TYPES_CRC16_ADLER_A,
    SENTIENT_ERROR_CHECKER_TYPES_CRC16_ADLER_B,
    SENTIENT_ERROR_CHECKER_TYPES_CRC16_CCITT,
    SENTIENT_ERROR_CHECKER_TYPES_CRC16_IBM,
    SENTIENT_ERROR_CHECKER_TYPES_CRC32_ADLER,
    SENTIENT_ERROR_CHECKER_TYPES_CRC32_IEEE_802_3,
    SENTIENT_ERROR_CHECKER_TYPES_CRC32_CASTAGNOLI,
    SENTIENT_ERROR_CHECKER_TYPES_CRC64_ISO,
    SENTIENT_ERROR_CHECKER_TYPES_CRC64_ECMA_182,
    SENTIENT_ERROR_CHECKER_TYPES_CRC128,
};

#ifdef __cplusplus
}
#endif

#endif