#ifndef __SENTIENT_CORE_FIELD_TYPES_H__
#define __SENTIENT_CORE_FIELD_TYPES_H__

/**
 * @file field_types.h
 * @author Jin (jaehwanspin@gmail.com)
 * @brief defines field types enumerations
 * @version 0.1
 * @date 2022-04-08
 *
 * @copyright Copyright (c) 2022
 *
 */

#ifdef __cplusplus
extern "C"
{
#endif

enum sentient_field_types
{
    SENTIENT_FIELD_TYPES_NONE,
    SENTIENT_FIELD_TYPES_U8,
    SENTIENT_FIELD_TYPES_U16,
    SENTIENT_FIELD_TYPES_U32,
    SENTIENT_FIELD_TYPES_U64,
    SENTIENT_FIELD_TYPES_I8,
    SENTIENT_FIELD_TYPES_I16,
    SENTIENT_FIELD_TYPES_I32,
    SENTIENT_FIELD_TYPES_I64,
    SENTIENT_FIELD_TYPES_F32,
    SENTIENT_FIELD_TYPES_F64,
    SENTIENT_FIELD_TYPES_BF8,
    SENTIENT_FIELD_TYPES_BF16,
    SENTIENT_FIELD_TYPES_BF32,
    SENTIENT_FIELD_TYPES_BF64,
    SENTIENT_FIELD_TYPES_STR8,
    SENTIENT_FIELD_TYPES_STR16,
    SENTIENT_FIELD_TYPES_STR32,
    SENTIENT_FIELD_TYPES_SCDT32,
    SENTIENT_FIELD_TYPES_SCDT64,
    SENTIENT_FIELD_TYPES_PT64,
    SENTIENT_FIELD_TYPES_MODEL,
    SENTIENT_FIELD_TYPES_PTR,
    SENTIENT_FIELD_TYPES_EXT,
};

#ifdef __cplusplus
}
#endif

#endif