//
// Copyright (c) 2016-2019 Jin (jaehwanspin@gmail.com)
//
// Distributed under the Boost Software License, Version 1.0. (See accompanying
// file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)
//
// Official repository: https://github.com/hyper-level-nerds/sentient
//
#
# ifndef SENTIENT_PREPROCESSOR_SEQ_FOR_EACH_PRODUCT_H
# define SENTIENT_PREPROCESSOR_SEQ_FOR_EACH_PRODUCT_H
#
# include <sentient/preprocessor/arithmetic/dec.h>
# include <sentient/preprocessor/config/config.h>
# include <sentient/preprocessor/control/if.h>
# include <sentient/preprocessor/repetition/for.h>
# include <sentient/preprocessor/seq/seq.h>
# include <sentient/preprocessor/seq/size.h>
# include <sentient/preprocessor/tuple/elem.h>
# include <sentient/preprocessor/tuple/rem.h>
#
# /* SNT_PP_SEQ_FOR_EACH_PRODUCT */
#
# define SNT_PP_SEQ_FOR_EACH_PRODUCT(macro, sets) SNT_PP_SEQ_FOR_EACH_PRODUCT_E(SNT_PP_FOR, macro, sets)
#
# /* SNT_PP_SEQ_FOR_EACH_PRODUCT_R */
#
# define SNT_PP_SEQ_FOR_EACH_PRODUCT_R(r, macro, sets) SNT_PP_SEQ_FOR_EACH_PRODUCT_E(SNT_PP_FOR_ ## r, macro, sets)
#
# if ~SNT_PP_CONFIG_FLAGS() & SNT_PP_CONFIG_EDG()
#    define SNT_PP_SEQ_FOR_EACH_PRODUCT_E(impl, macro, sets) impl((SNT_PP_SEQ_HEAD(sets)(nil), SNT_PP_SEQ_TAIL(sets)(nil), (nil), macro), SNT_PP_SEQ_FOR_EACH_PRODUCT_P, SNT_PP_SEQ_FOR_EACH_PRODUCT_O, SNT_PP_SEQ_FOR_EACH_PRODUCT_M_0)
# else
#    define SNT_PP_SEQ_FOR_EACH_PRODUCT_E(impl, macro, sets) SNT_PP_SEQ_FOR_EACH_PRODUCT_E_I(impl, macro, sets)
#    define SNT_PP_SEQ_FOR_EACH_PRODUCT_E_I(impl, macro, sets) impl((SNT_PP_SEQ_HEAD(sets)(nil), SNT_PP_SEQ_TAIL(sets)(nil), (nil), macro), SNT_PP_SEQ_FOR_EACH_PRODUCT_P, SNT_PP_SEQ_FOR_EACH_PRODUCT_O, SNT_PP_SEQ_FOR_EACH_PRODUCT_M_0)
# endif
#
# if SNT_PP_CONFIG_FLAGS() & SNT_PP_CONFIG_STRICT()
#    define SNT_PP_SEQ_FOR_EACH_PRODUCT_P(r, data) SNT_PP_SEQ_FOR_EACH_PRODUCT_P_I data
#    define SNT_PP_SEQ_FOR_EACH_PRODUCT_P_I(cset, rset, res, macro) SNT_PP_DEC(SNT_PP_SEQ_SIZE(cset))
# else
#    define SNT_PP_SEQ_FOR_EACH_PRODUCT_P(r, data) SNT_PP_DEC(SNT_PP_SEQ_SIZE(SNT_PP_TUPLE_ELEM(4, 0, data)))
# endif
#
# if ~SNT_PP_CONFIG_FLAGS() & SNT_PP_CONFIG_MWCC()
#    define SNT_PP_SEQ_FOR_EACH_PRODUCT_O(r, data) SNT_PP_SEQ_FOR_EACH_PRODUCT_O_I data
#    define SNT_PP_SEQ_FOR_EACH_PRODUCT_O_I(cset, rset, res, macro) (SNT_PP_SEQ_TAIL(cset), rset, res, macro)
# else
#    define SNT_PP_SEQ_FOR_EACH_PRODUCT_O(r, data) (SNT_PP_SEQ_TAIL(SNT_PP_TUPLE_ELEM(4, 0, data)), SNT_PP_TUPLE_ELEM(4, 1, data), SNT_PP_TUPLE_ELEM(4, 2, data), SNT_PP_TUPLE_ELEM(4, 3, data))
# endif
#
# define SNT_PP_SEQ_FOR_EACH_PRODUCT_C(data, i) SNT_PP_IF(SNT_PP_DEC(SNT_PP_SEQ_SIZE(SNT_PP_TUPLE_ELEM(4, 1, data))), SNT_PP_SEQ_FOR_EACH_PRODUCT_N_ ## i, SNT_PP_SEQ_FOR_EACH_PRODUCT_I)
#
# if ~SNT_PP_CONFIG_FLAGS() & SNT_PP_CONFIG_EDG()
#    define SNT_PP_SEQ_FOR_EACH_PRODUCT_I(r, data) SNT_PP_SEQ_FOR_EACH_PRODUCT_I_I(r, SNT_PP_TUPLE_ELEM(4, 0, data), SNT_PP_TUPLE_ELEM(4, 1, data), SNT_PP_TUPLE_ELEM(4, 2, data), SNT_PP_TUPLE_ELEM(4, 3, data))
# else
#    define SNT_PP_SEQ_FOR_EACH_PRODUCT_I(r, data) SNT_PP_SEQ_FOR_EACH_PRODUCT_I_IM(r, SNT_PP_TUPLE_REM_4 data)
#    define SNT_PP_SEQ_FOR_EACH_PRODUCT_I_IM(r, im) SNT_PP_SEQ_FOR_EACH_PRODUCT_I_I(r, im)
# endif
#
# define SNT_PP_SEQ_FOR_EACH_PRODUCT_I_I(r, cset, rset, res, macro) macro(r, SNT_PP_SEQ_TAIL(res (SNT_PP_SEQ_HEAD(cset))))
#
# if ~SNT_PP_CONFIG_FLAGS() & SNT_PP_CONFIG_MWCC()
#    define SNT_PP_SEQ_FOR_EACH_PRODUCT_H(data) SNT_PP_SEQ_FOR_EACH_PRODUCT_H_I data
# else
#    define SNT_PP_SEQ_FOR_EACH_PRODUCT_H(data) SNT_PP_SEQ_FOR_EACH_PRODUCT_H_I(SNT_PP_TUPLE_ELEM(4, 0, data), SNT_PP_TUPLE_ELEM(4, 1, data), SNT_PP_TUPLE_ELEM(4, 2, data), SNT_PP_TUPLE_ELEM(4, 3, data))
# endif
#
# define SNT_PP_SEQ_FOR_EACH_PRODUCT_H_I(cset, rset, res, macro) (SNT_PP_SEQ_HEAD(rset)(nil), SNT_PP_SEQ_TAIL(rset), res (SNT_PP_SEQ_HEAD(cset)), macro)
#
# define SNT_PP_SEQ_FOR_EACH_PRODUCT_M_0(r, data) SNT_PP_SEQ_FOR_EACH_PRODUCT_C(data, 0)(r, data)
# define SNT_PP_SEQ_FOR_EACH_PRODUCT_M_1(r, data) SNT_PP_SEQ_FOR_EACH_PRODUCT_C(data, 1)(r, data)
# define SNT_PP_SEQ_FOR_EACH_PRODUCT_M_2(r, data) SNT_PP_SEQ_FOR_EACH_PRODUCT_C(data, 2)(r, data)
# define SNT_PP_SEQ_FOR_EACH_PRODUCT_M_3(r, data) SNT_PP_SEQ_FOR_EACH_PRODUCT_C(data, 3)(r, data)
# define SNT_PP_SEQ_FOR_EACH_PRODUCT_M_4(r, data) SNT_PP_SEQ_FOR_EACH_PRODUCT_C(data, 4)(r, data)
# define SNT_PP_SEQ_FOR_EACH_PRODUCT_M_5(r, data) SNT_PP_SEQ_FOR_EACH_PRODUCT_C(data, 5)(r, data)
# define SNT_PP_SEQ_FOR_EACH_PRODUCT_M_6(r, data) SNT_PP_SEQ_FOR_EACH_PRODUCT_C(data, 6)(r, data)
# define SNT_PP_SEQ_FOR_EACH_PRODUCT_M_7(r, data) SNT_PP_SEQ_FOR_EACH_PRODUCT_C(data, 7)(r, data)
# define SNT_PP_SEQ_FOR_EACH_PRODUCT_M_8(r, data) SNT_PP_SEQ_FOR_EACH_PRODUCT_C(data, 8)(r, data)
# define SNT_PP_SEQ_FOR_EACH_PRODUCT_M_9(r, data) SNT_PP_SEQ_FOR_EACH_PRODUCT_C(data, 9)(r, data)
# define SNT_PP_SEQ_FOR_EACH_PRODUCT_M_10(r, data) SNT_PP_SEQ_FOR_EACH_PRODUCT_C(data, 10)(r, data)
# define SNT_PP_SEQ_FOR_EACH_PRODUCT_M_11(r, data) SNT_PP_SEQ_FOR_EACH_PRODUCT_C(data, 11)(r, data)
# define SNT_PP_SEQ_FOR_EACH_PRODUCT_M_12(r, data) SNT_PP_SEQ_FOR_EACH_PRODUCT_C(data, 12)(r, data)
# define SNT_PP_SEQ_FOR_EACH_PRODUCT_M_13(r, data) SNT_PP_SEQ_FOR_EACH_PRODUCT_C(data, 13)(r, data)
# define SNT_PP_SEQ_FOR_EACH_PRODUCT_M_14(r, data) SNT_PP_SEQ_FOR_EACH_PRODUCT_C(data, 14)(r, data)
# define SNT_PP_SEQ_FOR_EACH_PRODUCT_M_15(r, data) SNT_PP_SEQ_FOR_EACH_PRODUCT_C(data, 15)(r, data)
# define SNT_PP_SEQ_FOR_EACH_PRODUCT_M_16(r, data) SNT_PP_SEQ_FOR_EACH_PRODUCT_C(data, 16)(r, data)
# define SNT_PP_SEQ_FOR_EACH_PRODUCT_M_17(r, data) SNT_PP_SEQ_FOR_EACH_PRODUCT_C(data, 17)(r, data)
# define SNT_PP_SEQ_FOR_EACH_PRODUCT_M_18(r, data) SNT_PP_SEQ_FOR_EACH_PRODUCT_C(data, 18)(r, data)
# define SNT_PP_SEQ_FOR_EACH_PRODUCT_M_19(r, data) SNT_PP_SEQ_FOR_EACH_PRODUCT_C(data, 19)(r, data)
# define SNT_PP_SEQ_FOR_EACH_PRODUCT_M_20(r, data) SNT_PP_SEQ_FOR_EACH_PRODUCT_C(data, 20)(r, data)
# define SNT_PP_SEQ_FOR_EACH_PRODUCT_M_21(r, data) SNT_PP_SEQ_FOR_EACH_PRODUCT_C(data, 21)(r, data)
# define SNT_PP_SEQ_FOR_EACH_PRODUCT_M_22(r, data) SNT_PP_SEQ_FOR_EACH_PRODUCT_C(data, 22)(r, data)
# define SNT_PP_SEQ_FOR_EACH_PRODUCT_M_23(r, data) SNT_PP_SEQ_FOR_EACH_PRODUCT_C(data, 23)(r, data)
# define SNT_PP_SEQ_FOR_EACH_PRODUCT_M_24(r, data) SNT_PP_SEQ_FOR_EACH_PRODUCT_C(data, 24)(r, data)
# define SNT_PP_SEQ_FOR_EACH_PRODUCT_M_25(r, data) SNT_PP_SEQ_FOR_EACH_PRODUCT_C(data, 25)(r, data)
#
# define SNT_PP_SEQ_FOR_EACH_PRODUCT_N_0(r, data) SNT_PP_FOR_ ## r(SNT_PP_SEQ_FOR_EACH_PRODUCT_H(data), SNT_PP_SEQ_FOR_EACH_PRODUCT_P, SNT_PP_SEQ_FOR_EACH_PRODUCT_O, SNT_PP_SEQ_FOR_EACH_PRODUCT_M_1)
# define SNT_PP_SEQ_FOR_EACH_PRODUCT_N_1(r, data) SNT_PP_FOR_ ## r(SNT_PP_SEQ_FOR_EACH_PRODUCT_H(data), SNT_PP_SEQ_FOR_EACH_PRODUCT_P, SNT_PP_SEQ_FOR_EACH_PRODUCT_O, SNT_PP_SEQ_FOR_EACH_PRODUCT_M_2)
# define SNT_PP_SEQ_FOR_EACH_PRODUCT_N_2(r, data) SNT_PP_FOR_ ## r(SNT_PP_SEQ_FOR_EACH_PRODUCT_H(data), SNT_PP_SEQ_FOR_EACH_PRODUCT_P, SNT_PP_SEQ_FOR_EACH_PRODUCT_O, SNT_PP_SEQ_FOR_EACH_PRODUCT_M_3)
# define SNT_PP_SEQ_FOR_EACH_PRODUCT_N_3(r, data) SNT_PP_FOR_ ## r(SNT_PP_SEQ_FOR_EACH_PRODUCT_H(data), SNT_PP_SEQ_FOR_EACH_PRODUCT_P, SNT_PP_SEQ_FOR_EACH_PRODUCT_O, SNT_PP_SEQ_FOR_EACH_PRODUCT_M_4)
# define SNT_PP_SEQ_FOR_EACH_PRODUCT_N_4(r, data) SNT_PP_FOR_ ## r(SNT_PP_SEQ_FOR_EACH_PRODUCT_H(data), SNT_PP_SEQ_FOR_EACH_PRODUCT_P, SNT_PP_SEQ_FOR_EACH_PRODUCT_O, SNT_PP_SEQ_FOR_EACH_PRODUCT_M_5)
# define SNT_PP_SEQ_FOR_EACH_PRODUCT_N_5(r, data) SNT_PP_FOR_ ## r(SNT_PP_SEQ_FOR_EACH_PRODUCT_H(data), SNT_PP_SEQ_FOR_EACH_PRODUCT_P, SNT_PP_SEQ_FOR_EACH_PRODUCT_O, SNT_PP_SEQ_FOR_EACH_PRODUCT_M_6)
# define SNT_PP_SEQ_FOR_EACH_PRODUCT_N_6(r, data) SNT_PP_FOR_ ## r(SNT_PP_SEQ_FOR_EACH_PRODUCT_H(data), SNT_PP_SEQ_FOR_EACH_PRODUCT_P, SNT_PP_SEQ_FOR_EACH_PRODUCT_O, SNT_PP_SEQ_FOR_EACH_PRODUCT_M_7)
# define SNT_PP_SEQ_FOR_EACH_PRODUCT_N_7(r, data) SNT_PP_FOR_ ## r(SNT_PP_SEQ_FOR_EACH_PRODUCT_H(data), SNT_PP_SEQ_FOR_EACH_PRODUCT_P, SNT_PP_SEQ_FOR_EACH_PRODUCT_O, SNT_PP_SEQ_FOR_EACH_PRODUCT_M_8)
# define SNT_PP_SEQ_FOR_EACH_PRODUCT_N_8(r, data) SNT_PP_FOR_ ## r(SNT_PP_SEQ_FOR_EACH_PRODUCT_H(data), SNT_PP_SEQ_FOR_EACH_PRODUCT_P, SNT_PP_SEQ_FOR_EACH_PRODUCT_O, SNT_PP_SEQ_FOR_EACH_PRODUCT_M_9)
# define SNT_PP_SEQ_FOR_EACH_PRODUCT_N_9(r, data) SNT_PP_FOR_ ## r(SNT_PP_SEQ_FOR_EACH_PRODUCT_H(data), SNT_PP_SEQ_FOR_EACH_PRODUCT_P, SNT_PP_SEQ_FOR_EACH_PRODUCT_O, SNT_PP_SEQ_FOR_EACH_PRODUCT_M_10)
# define SNT_PP_SEQ_FOR_EACH_PRODUCT_N_10(r, data) SNT_PP_FOR_ ## r(SNT_PP_SEQ_FOR_EACH_PRODUCT_H(data), SNT_PP_SEQ_FOR_EACH_PRODUCT_P, SNT_PP_SEQ_FOR_EACH_PRODUCT_O, SNT_PP_SEQ_FOR_EACH_PRODUCT_M_11)
# define SNT_PP_SEQ_FOR_EACH_PRODUCT_N_11(r, data) SNT_PP_FOR_ ## r(SNT_PP_SEQ_FOR_EACH_PRODUCT_H(data), SNT_PP_SEQ_FOR_EACH_PRODUCT_P, SNT_PP_SEQ_FOR_EACH_PRODUCT_O, SNT_PP_SEQ_FOR_EACH_PRODUCT_M_12)
# define SNT_PP_SEQ_FOR_EACH_PRODUCT_N_12(r, data) SNT_PP_FOR_ ## r(SNT_PP_SEQ_FOR_EACH_PRODUCT_H(data), SNT_PP_SEQ_FOR_EACH_PRODUCT_P, SNT_PP_SEQ_FOR_EACH_PRODUCT_O, SNT_PP_SEQ_FOR_EACH_PRODUCT_M_13)
# define SNT_PP_SEQ_FOR_EACH_PRODUCT_N_13(r, data) SNT_PP_FOR_ ## r(SNT_PP_SEQ_FOR_EACH_PRODUCT_H(data), SNT_PP_SEQ_FOR_EACH_PRODUCT_P, SNT_PP_SEQ_FOR_EACH_PRODUCT_O, SNT_PP_SEQ_FOR_EACH_PRODUCT_M_14)
# define SNT_PP_SEQ_FOR_EACH_PRODUCT_N_14(r, data) SNT_PP_FOR_ ## r(SNT_PP_SEQ_FOR_EACH_PRODUCT_H(data), SNT_PP_SEQ_FOR_EACH_PRODUCT_P, SNT_PP_SEQ_FOR_EACH_PRODUCT_O, SNT_PP_SEQ_FOR_EACH_PRODUCT_M_15)
# define SNT_PP_SEQ_FOR_EACH_PRODUCT_N_15(r, data) SNT_PP_FOR_ ## r(SNT_PP_SEQ_FOR_EACH_PRODUCT_H(data), SNT_PP_SEQ_FOR_EACH_PRODUCT_P, SNT_PP_SEQ_FOR_EACH_PRODUCT_O, SNT_PP_SEQ_FOR_EACH_PRODUCT_M_16)
# define SNT_PP_SEQ_FOR_EACH_PRODUCT_N_16(r, data) SNT_PP_FOR_ ## r(SNT_PP_SEQ_FOR_EACH_PRODUCT_H(data), SNT_PP_SEQ_FOR_EACH_PRODUCT_P, SNT_PP_SEQ_FOR_EACH_PRODUCT_O, SNT_PP_SEQ_FOR_EACH_PRODUCT_M_17)
# define SNT_PP_SEQ_FOR_EACH_PRODUCT_N_17(r, data) SNT_PP_FOR_ ## r(SNT_PP_SEQ_FOR_EACH_PRODUCT_H(data), SNT_PP_SEQ_FOR_EACH_PRODUCT_P, SNT_PP_SEQ_FOR_EACH_PRODUCT_O, SNT_PP_SEQ_FOR_EACH_PRODUCT_M_18)
# define SNT_PP_SEQ_FOR_EACH_PRODUCT_N_18(r, data) SNT_PP_FOR_ ## r(SNT_PP_SEQ_FOR_EACH_PRODUCT_H(data), SNT_PP_SEQ_FOR_EACH_PRODUCT_P, SNT_PP_SEQ_FOR_EACH_PRODUCT_O, SNT_PP_SEQ_FOR_EACH_PRODUCT_M_19)
# define SNT_PP_SEQ_FOR_EACH_PRODUCT_N_19(r, data) SNT_PP_FOR_ ## r(SNT_PP_SEQ_FOR_EACH_PRODUCT_H(data), SNT_PP_SEQ_FOR_EACH_PRODUCT_P, SNT_PP_SEQ_FOR_EACH_PRODUCT_O, SNT_PP_SEQ_FOR_EACH_PRODUCT_M_20)
# define SNT_PP_SEQ_FOR_EACH_PRODUCT_N_20(r, data) SNT_PP_FOR_ ## r(SNT_PP_SEQ_FOR_EACH_PRODUCT_H(data), SNT_PP_SEQ_FOR_EACH_PRODUCT_P, SNT_PP_SEQ_FOR_EACH_PRODUCT_O, SNT_PP_SEQ_FOR_EACH_PRODUCT_M_21)
# define SNT_PP_SEQ_FOR_EACH_PRODUCT_N_21(r, data) SNT_PP_FOR_ ## r(SNT_PP_SEQ_FOR_EACH_PRODUCT_H(data), SNT_PP_SEQ_FOR_EACH_PRODUCT_P, SNT_PP_SEQ_FOR_EACH_PRODUCT_O, SNT_PP_SEQ_FOR_EACH_PRODUCT_M_22)
# define SNT_PP_SEQ_FOR_EACH_PRODUCT_N_22(r, data) SNT_PP_FOR_ ## r(SNT_PP_SEQ_FOR_EACH_PRODUCT_H(data), SNT_PP_SEQ_FOR_EACH_PRODUCT_P, SNT_PP_SEQ_FOR_EACH_PRODUCT_O, SNT_PP_SEQ_FOR_EACH_PRODUCT_M_23)
# define SNT_PP_SEQ_FOR_EACH_PRODUCT_N_23(r, data) SNT_PP_FOR_ ## r(SNT_PP_SEQ_FOR_EACH_PRODUCT_H(data), SNT_PP_SEQ_FOR_EACH_PRODUCT_P, SNT_PP_SEQ_FOR_EACH_PRODUCT_O, SNT_PP_SEQ_FOR_EACH_PRODUCT_M_24)
# define SNT_PP_SEQ_FOR_EACH_PRODUCT_N_24(r, data) SNT_PP_FOR_ ## r(SNT_PP_SEQ_FOR_EACH_PRODUCT_H(data), SNT_PP_SEQ_FOR_EACH_PRODUCT_P, SNT_PP_SEQ_FOR_EACH_PRODUCT_O, SNT_PP_SEQ_FOR_EACH_PRODUCT_M_25)
# define SNT_PP_SEQ_FOR_EACH_PRODUCT_N_25(r, data) SNT_PP_FOR_ ## r(SNT_PP_SEQ_FOR_EACH_PRODUCT_H(data), SNT_PP_SEQ_FOR_EACH_PRODUCT_P, SNT_PP_SEQ_FOR_EACH_PRODUCT_O, SNT_PP_SEQ_FOR_EACH_PRODUCT_M_26)
#
# endif
